#checkov:skip=CKV_DOCKER_2:Uniquement utilisé en local pour le dev
#checkov:skip=CKV_DOCKER_3:Uniquement utilisé en local pour le dev
FROM ghcr.io/etalab-ia/evalap/evalap:main-latest
COPY ./src/metriques_personnalisees_evalap/[^_]*  /app/evalap/api/metrics/