name: L'intégration continue
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Construction du projet de test de MesQuestionsCyber
    runs-on: ubuntu-latest

    env:
      ALBERT_API_KEY: une-fausse-clef
      COLLECTION_ID_ANSSI_LAB: 42
      MODE: test

    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Installer Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: "pyproject.toml"

      - name: Installer uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0

      - name: Installer les dépendances
        run: uv sync

      - name: Contrôler le format du code
        run: uv run ruff check

      - name: Contrôler les types
        run: uv run mypy

      - name: Exécuter les tests
        run: uv run pytest
